### ISSUE TITLE
[Feature]: Transpose the VS Code extension into a WebStorm Plugin

### ISSUE THREAD

**Issue by OxyFlax** [AmadeusITGroup/otter#798] opened 2023-09-14 17:19 UTC
### Context

There's a great extension built for VS Code but many people across or organisation are using WebStorm and it would be nice to get the same features.
Additional context, WebStorm >>> VS Code 😜 

### Proposal

Build a plugin for WebStorm with same functionalities as the VS Code extension.

**Comment by kpanot** [comment] 2023-09-15 08:33
duplicate of #799

**Closed** 2023-09-15 08:33 UTC
Labels: duplicate, enhancement
